apiVersion: v2
name: libretranslate
description: A Helm chart for Kubernetes to deploy LibreTranslate API
home: https://ricardoalonso.github.io/libretranslate-helm-chart/
sources:
  - https://github.com/LibreTranslate/LibreTranslate/
  - https://github.com/ricardoalonso/libretranslate-helm-chart/
icon: https://libretranslate.com/static/favicon.ico
version: 0.2.2
